### ISSUE TITLE
Windows環境でエンコードエラーが発生する / Encoding Error in Windows

### ISSUE THREAD

**Issue by ikimiti4408** [ekurerice/jp_cvu_normalizer#1]
突然のissueを失礼します。

## 概要
Windows11のPython3環境において、JaCvuNormalizerクラスのインスタンス化をした際に、`reader.py`にて`UnicodeDecodeError 'cp932' codec can't decode byte 0x87 in position 286: illegal multibyte sequence`が発生します。
Windows環境固有の問題だと思われます。

## 再現方法
WIndowsで実行します。
事前に`pip install ja-cvu-normalizer`をしておきます。

```python
from ja_cvu_normalizer.ja_cvu_normalizer import JaCvuNormalizer
Ja_cvu_normalizer = JaCvuNormalizer()
```
## 原因
`reader.py`45行目の`with open()`にて`encoding`を指定していないことが原因と思われます。  
  
----------------------------------
    
Sorry to send you an "issue" out of the blue.

## Problem
In Python3 on Windows 11, when instantiating the JaCvuNormalizer class, I get `UnicodeDecodeError 'cp932' codec can't decode byte 0x87 in position 286: illegal multibyte sequence` in `reader.py`.
This seems to be a problem specific to the Windows environment.

## How to reproduce
Run on WIndows.
Do `pip install ja-cvu-normalizer` beforehand.

```python
from ja_cvu_normalizer.ja_cvu_normalizer import JaCvuNormalizer
Ja_cvu_normalizer = JaCvuNormalizer()
```
## Cause
The reason may be that `encoding` is not specified in `with open()` in `reader.py` line 45.

**Comment by ekurerice** [comment]
@ikimiti4408 さま

issueを起案いただきましてありがとうございます。
PRについて確認いたします。

**Comment by ekurerice** [comment]
@ikimiti4408 
PRマージいたしました。pypi上のパッケージも更新しましたので、ご確認願います。

**Comment by ikimiti4408** [comment]
@ekurerice 
確認・マージありがとうございます。
パッケージをアップデートしたところ、更新が反映されており、エンコードエラーも解決しておりました。
issue,PRに迅速に対応していただきありがとうございました。
